name: CI

on:
    push:
        branches: [main]
        tags:
            - 'v*'
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18, 20]

        steps:
            - uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 8

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Type check
              run: pnpm type-check

            - name: Lint
              run: pnpm lint

            - name: Format check
              run: pnpm format:check

            - name: Test
              run: pnpm test:ci

            - name: Build
              run: pnpm build

    publish:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

        steps:
            - uses: actions/checkout@v4
              with:
                  # This makes Actions fetch all Git history so that Changesets can generate changelogs
                  fetch-depth: 0

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 8

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Create Release Pull Request or Publish to NPM
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
